spring.application.name=trace-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/trace_db
spring.datasource.username=postgres
spring.datasource.password=pgKaPassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=DfLdHyHFBbLThhok9oXSZuqKau90YQgldBKVIfuWox1
jwt.expiration=604800000